[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  BUN_VERSION = "1.3.9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  timeout = 26

[functions."___netlify-server-handler"]
  timeout = 26
